
/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT! *
 *                                                              *
 * FILE NAME: etpu_sm_auto.h       COPYRIGHT (c) Freescale 2004 *
 *                                      All Rights Reserved     *
 * This file generated by:                                      *
 * $RCSfile: etpuc_sm.c,v $ $Revision: 1.4 $
 *                                                              *
 * This file provides an interface between eTPU code and CPU    *
 * code. All references to the SM function should be made with  *
 * information in this file. This allows only symbolic          *
 * information to be referenced which allows the eTPU code to be*
 * optimized without effecting the CPU code.                    *
 ****************************************************************/
#ifndef _ETPU_SM_AUTO_H_
#define _ETPU_SM_AUTO_H_

/* Function Configuration Information */
#define FS_ETPU_SM_FUNCTION_NUMBER   9 
#define FS_ETPU_SM_TABLE_SELECT     0 
#define FS_ETPU_SM_NUM_PARMS        0x0028 

/* Host Service Request Definitions */
#define FS_ETPU_SM_INIT_LOW         7 
#define FS_ETPU_SM_INIT_HIGH        6 
#define FS_ETPU_SM_STOP_LOW         5 
#define FS_ETPU_SM_STOP_HIGH        4 
#define FS_ETPU_SM_MOVE             2 

/* Function Mode Definitions */
#define FS_ETPU_SM_FULL_STEP        0
#define FS_ETPU_SM_HALF_STEP        2

/* Value Definitions */
#define FS_ETPU_SM_STEPPING         1 
#define FS_ETPU_SM_STEPPING_OFF     0 
#define FS_ETPU_SM_STEPPING_ON      1 

#define FS_ETPU_SM_DIRECTION        2 
#define FS_ETPU_SM_DIRECTION_LEFT   0 
#define FS_ETPU_SM_DIRECTION_RIGHT  2 

#define FS_ETPU_SM_SLEW             4 
#define FS_ETPU_SM_SLEW_OFF         0 
#define FS_ETPU_SM_SLEW_ON          4 

/* Parameter Definitions */
#define FS_ETPU_SM_DESIREDPOSITION_OFFSET  0x0001
#define FS_ETPU_SM_CURRENTPOSITION_OFFSET  0x0005
#define FS_ETPU_SM_STARTPERIOD_OFFSET      0x0009
#define FS_ETPU_SM_SLEWPERIOD_OFFSET       0x000D
#define FS_ETPU_SM_CHANNELS_OFFSET         0x0011
#define FS_ETPU_SM_PINSEQUENCE_OFFSET      0x0015
#define FS_ETPU_SM_ACCELTBLSIZE_OFFSET     0x0019
#define FS_ETPU_SM_ACCELTBL_OFFSET         0x001D
#define FS_ETPU_SM_FLAGS_OFFSET            0x0000

#endif /* _ETPU_SM_AUTO_H_ */

