
/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT! *
 *                                                              *
 * FILE NAME: etpu_test_auto.h     COPYRIGHT (c) Freescale 2004 *
 *                                      All Rights Reserved     *
 * This file generated by:                                      *
 * $RCSfile: etpuc_test.c,v $ $Revision: 1.3 $
 *                                                              *
 * This file provides an interface between eTPU code and CPU    *
 * code. All references to the TEST function should be made with*
 * information in this file. This allows only symbolic          *
 * information to be referenced which allows the eTPU code to be*
 * optimized without effecting the CPU code.                    *
 ****************************************************************/
#ifndef _ETPU_TEST_AUTO_H_
#define _ETPU_TEST_AUTO_H_

/* Function Configuration Information */
#define ETPU_TEST_FUNCTION_NUMBER  7 
#define ETPU_TEST_TABLE_SELECT 0 
#define ETPU_TEST_NUM_PARMS 0x0008 

/* Host Service Request Definitions */
#define FS_ETPU_TEST_GENERATE_INTERRUPT 7 
#define FS_ETPU_TEST_GENERATE_DTR 6 
#define FS_ETPU_TEST_GENERATE_LINK 5 
#define FS_ETPU_TEST_GLOBAL_EXCEPTION 4 

/* Parameter Definitions */
#define ETPU_TEST_CHANNEL_OFFSET  0x0001

#endif /* _ETPU_TEST_AUTO_H_ */

